# Generated by Django 4.2.7 on 2023-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
